-- CREATE OR REPLACE STAGE BRONZE_LAYER.gcs_realtime_stage
--   URL = 'gcs://snowflake-realtime-ds-pipeline/'
--   STORAGE_INTEGRATION = GCS_INT
--   FILE_FORMAT = BRONZE_LAYER.CSV_FORMAT;

CREATE OR REPLACE PIPE BRONZE_LAYER.PIPE_ORDERS_RAW
AUTO_INGEST = TRUE
INTEGRATION = 'GCS_REALTIME_PIPELINE_NOTIFICATION_INT'
AS
COPY INTO BRONZE_LAYER.ORDERS_RAW
FROM @BRONZE_LAYER.GCS_REALTIME_STAGE/orders/
FILE_FORMAT = (FORMAT_NAME = BRONZE_LAYER.CSV_FORMAT);

CREATE OR REPLACE PIPE BRONZE_LAYER.PIPE_ORDER_ITEMS_RAW
  AUTO_INGEST = TRUE
  INTEGRATION = 'GCS_REALTIME_PIPELINE_NOTIFICATION_INT' 
AS
  COPY INTO BRONZE_LAYER.ORDER_ITEMS_RAW
  FROM @BRONZE_LAYER.gcs_realtime_stage/order_items/
  FILE_FORMAT = (FORMAT_NAME = BRONZE_LAYER.CSV_FORMAT);

CREATE OR REPLACE PIPE BRONZE_LAYER.PIPE_PAYMENTS_RAW
  AUTO_INGEST = TRUE
  INTEGRATION = 'GCS_REALTIME_PIPELINE_NOTIFICATION_INT' 
AS
  COPY INTO BRONZE_LAYER.PAYMENTS_RAW
  FROM @BRONZE_LAYER.gcs_realtime_stage/order_payments/
  FILE_FORMAT = (FORMAT_NAME = BRONZE_LAYER.CSV_FORMAT);