-- =========================================================
-- V1.1.7 - Silver layer tasks (exact production SQL)
-- 4 MERGE tasks (weekly batch) + 4 WATCHER tasks (every 4h)
-- =========================================================

-- ---- WEEKLY MERGE TASKS ----

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.SILVER_LAYER.TASK_MERGE_CUSTOMERS
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 2 * * SUN America/New_York'
    WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.BRONZE_LAYER.CUSTOMER_RAW_STREAM')
AS
MERGE INTO ECOMMERCE_DB.SILVER_LAYER.CUSTOMERS tgt
USING (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_UNIQUE_ID,
        TRIM(CUSTOMER_ZIP_CODE_PREFIX) AS ZIP_CODE,
        INITCAP(TRIM(CUSTOMER_CITY))   AS CITY,
        UPPER(TRIM(CUSTOMER_STATE))    AS STATE
    FROM ECOMMERCE_DB.BRONZE_LAYER.CUSTOMER_RAW_STREAM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY CUSTOMER_ID) = 1
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
    tgt.CUSTOMER_UNIQUE_ID = src.CUSTOMER_UNIQUE_ID,
    tgt.ZIP_CODE           = src.ZIP_CODE,
    tgt.CITY               = src.CITY,
    tgt.STATE              = src.STATE,
    tgt.UPDATED_AT         = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (CUSTOMER_ID, CUSTOMER_UNIQUE_ID, ZIP_CODE, CITY, STATE, LOADED_AT, UPDATED_AT)
VALUES
    (src.CUSTOMER_ID, src.CUSTOMER_UNIQUE_ID, src.ZIP_CODE, src.CITY, src.STATE,
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.SILVER_LAYER.TASK_MERGE_SELLERS
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 2 * * SUN America/New_York'
    WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.BRONZE_LAYER.SELLERS_RAW_STREAM')
AS
MERGE INTO ECOMMERCE_DB.SILVER_LAYER.SELLERS tgt
USING (
    SELECT
        SELLER_ID,
        TRIM(SELLER_ZIP_CODE_PREFIX) AS ZIP_CODE,
        INITCAP(TRIM(SELLER_CITY))   AS CITY,
        UPPER(TRIM(SELLER_STATE))    AS STATE
    FROM ECOMMERCE_DB.BRONZE_LAYER.SELLERS_RAW_STREAM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SELLER_ID ORDER BY SELLER_ID) = 1
) src
ON tgt.SELLER_ID = src.SELLER_ID
WHEN MATCHED THEN UPDATE SET
    tgt.ZIP_CODE   = src.ZIP_CODE,
    tgt.CITY       = src.CITY,
    tgt.STATE      = src.STATE,
    tgt.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (SELLER_ID, ZIP_CODE, CITY, STATE, LOADED_AT, UPDATED_AT)
VALUES
    (src.SELLER_ID, src.ZIP_CODE, src.CITY, src.STATE,
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.SILVER_LAYER.TASK_MERGE_PRODUCTS
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 2 * * SUN America/New_York'
    WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.BRONZE_LAYER.PRODUCTS_RAW_STREAM')
AS
MERGE INTO ECOMMERCE_DB.SILVER_LAYER.PRODUCTS tgt
USING (
    SELECT
        p.PRODUCT_ID,
        COALESCE(t.PRODUCT_CATEGORY_NAME_ENGLISH, p.PRODUCT_CATEGORY_NAME) AS PRODUCT_CATEGORY,
        p.PRODUCT_WEIGHT_G,
        p.PRODUCT_LENGTH_CM,
        p.PRODUCT_HEIGHT_CM,
        p.PRODUCT_WIDTH_CM,
        ROUND(p.PRODUCT_LENGTH_CM * p.PRODUCT_HEIGHT_CM * p.PRODUCT_WIDTH_CM, 2) AS VOLUME_CM3
    FROM ECOMMERCE_DB.BRONZE_LAYER.PRODUCTS_RAW_STREAM p
    LEFT JOIN ECOMMERCE_DB.BRONZE_LAYER.PRODUCT_CATEGORY_TRANSLATION_RAW t
      ON p.PRODUCT_CATEGORY_NAME = t.PRODUCT_CATEGORY_NAME
) src
ON tgt.PRODUCT_ID = src.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET
    tgt.PRODUCT_CATEGORY  = src.PRODUCT_CATEGORY,
    tgt.PRODUCT_WEIGHT_G  = src.PRODUCT_WEIGHT_G,
    tgt.PRODUCT_LENGTH_CM = src.PRODUCT_LENGTH_CM,
    tgt.PRODUCT_HEIGHT_CM = src.PRODUCT_HEIGHT_CM,
    tgt.PRODUCT_WIDTH_CM  = src.PRODUCT_WIDTH_CM,
    tgt.VOLUME_CM3        = src.VOLUME_CM3,
    tgt.UPDATED_AT        = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_WEIGHT_G, PRODUCT_LENGTH_CM,
     PRODUCT_HEIGHT_CM, PRODUCT_WIDTH_CM, VOLUME_CM3, LOADED_AT, UPDATED_AT)
VALUES
    (src.PRODUCT_ID, src.PRODUCT_CATEGORY, src.PRODUCT_WEIGHT_G, src.PRODUCT_LENGTH_CM,
     src.PRODUCT_HEIGHT_CM, src.PRODUCT_WIDTH_CM, src.VOLUME_CM3,
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.SILVER_LAYER.TASK_MERGE_GEOLOCATION
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 2 * * SUN America/New_York'
    WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.BRONZE_LAYER.GEOLOCATION_RAW_STREAM')
AS
MERGE INTO ECOMMERCE_DB.SILVER_LAYER.GEOLOCATION tgt
USING (
    SELECT
        GEOLOCATION_ZIP_CODE_PREFIX,
        AVG(GEOLOCATION_LAT)            AS GEOLOCATION_LAT,
        AVG(GEOLOCATION_LNG)            AS GEOLOCATION_LNG,
        INITCAP(TRIM(GEOLOCATION_CITY)) AS CITY,
        UPPER(TRIM(GEOLOCATION_STATE))  AS STATE
    FROM ECOMMERCE_DB.BRONZE_LAYER.GEOLOCATION_RAW_STREAM
    GROUP BY GEOLOCATION_ZIP_CODE_PREFIX, INITCAP(TRIM(GEOLOCATION_CITY)), UPPER(TRIM(GEOLOCATION_STATE))
) src
ON tgt.GEOLOCATION_ZIP_CODE_PREFIX = src.GEOLOCATION_ZIP_CODE_PREFIX
WHEN MATCHED THEN UPDATE SET
    tgt.GEOLOCATION_LAT = src.GEOLOCATION_LAT,
    tgt.GEOLOCATION_LNG = src.GEOLOCATION_LNG,
    tgt.CITY            = src.CITY,
    tgt.STATE           = src.STATE,
    tgt.UPDATED_AT      = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (GEOLOCATION_ZIP_CODE_PREFIX, GEOLOCATION_LAT, GEOLOCATION_LNG, CITY, STATE, LOADED_AT, UPDATED_AT)
VALUES
    (src.GEOLOCATION_ZIP_CODE_PREFIX, src.GEOLOCATION_LAT, src.GEOLOCATION_LNG,
     src.CITY, src.STATE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- ---- WATCHER TASKS (every 4 hours - higher frequency refresh) ----

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.SILVER_LAYER.TASK_WATCHER_CUSTOMERS
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 */4 * * * America/New_York'
    WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.BRONZE_LAYER.CUSTOMER_RAW_STREAM')
AS
MERGE INTO ECOMMERCE_DB.SILVER_LAYER.CUSTOMERS tgt
USING (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_UNIQUE_ID,
        TRIM(CUSTOMER_ZIP_CODE_PREFIX) AS ZIP_CODE,
        INITCAP(TRIM(CUSTOMER_CITY))   AS CITY,
        UPPER(TRIM(CUSTOMER_STATE))    AS STATE
    FROM ECOMMERCE_DB.BRONZE_LAYER.CUSTOMER_RAW_STREAM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY CUSTOMER_ID) = 1
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
    tgt.CUSTOMER_UNIQUE_ID = src.CUSTOMER_UNIQUE_ID,
    tgt.ZIP_CODE           = src.ZIP_CODE,
    tgt.CITY               = src.CITY,
    tgt.STATE              = src.STATE,
    tgt.UPDATED_AT         = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (CUSTOMER_ID, CUSTOMER_UNIQUE_ID, ZIP_CODE, CITY, STATE, LOADED_AT, UPDATED_AT)
VALUES
    (src.CUSTOMER_ID, src.CUSTOMER_UNIQUE_ID, src.ZIP_CODE, src.CITY, src.STATE,
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.SILVER_LAYER.TASK_WATCHER_SELLERS
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 */4 * * * America/New_York'
    WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.BRONZE_LAYER.SELLERS_RAW_STREAM')
AS
MERGE INTO ECOMMERCE_DB.SILVER_LAYER.SELLERS tgt
USING (
    SELECT
        SELLER_ID,
        TRIM(SELLER_ZIP_CODE_PREFIX) AS ZIP_CODE,
        INITCAP(TRIM(SELLER_CITY))   AS CITY,
        UPPER(TRIM(SELLER_STATE))    AS STATE
    FROM ECOMMERCE_DB.BRONZE_LAYER.SELLERS_RAW_STREAM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SELLER_ID ORDER BY SELLER_ID) = 1
) src
ON tgt.SELLER_ID = src.SELLER_ID
WHEN MATCHED THEN UPDATE SET
    tgt.ZIP_CODE   = src.ZIP_CODE,
    tgt.CITY       = src.CITY,
    tgt.STATE      = src.STATE,
    tgt.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (SELLER_ID, ZIP_CODE, CITY, STATE, LOADED_AT, UPDATED_AT)
VALUES
    (src.SELLER_ID, src.ZIP_CODE, src.CITY, src.STATE,
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.SILVER_LAYER.TASK_WATCHER_PRODUCTS
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 */4 * * * America/New_York'
    WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.BRONZE_LAYER.PRODUCTS_RAW_STREAM')
AS
MERGE INTO ECOMMERCE_DB.SILVER_LAYER.PRODUCTS tgt
USING (
    SELECT
        p.PRODUCT_ID,
        COALESCE(t.PRODUCT_CATEGORY_NAME_ENGLISH, p.PRODUCT_CATEGORY_NAME) AS PRODUCT_CATEGORY,
        p.PRODUCT_WEIGHT_G,
        p.PRODUCT_LENGTH_CM,
        p.PRODUCT_HEIGHT_CM,
        p.PRODUCT_WIDTH_CM,
        ROUND(p.PRODUCT_LENGTH_CM * p.PRODUCT_HEIGHT_CM * p.PRODUCT_WIDTH_CM, 2) AS VOLUME_CM3
    FROM ECOMMERCE_DB.BRONZE_LAYER.PRODUCTS_RAW_STREAM p
    LEFT JOIN ECOMMERCE_DB.BRONZE_LAYER.PRODUCT_CATEGORY_TRANSLATION_RAW t
      ON p.PRODUCT_CATEGORY_NAME = t.PRODUCT_CATEGORY_NAME
) src
ON tgt.PRODUCT_ID = src.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET
    tgt.PRODUCT_CATEGORY  = src.PRODUCT_CATEGORY,
    tgt.PRODUCT_WEIGHT_G  = src.PRODUCT_WEIGHT_G,
    tgt.PRODUCT_LENGTH_CM = src.PRODUCT_LENGTH_CM,
    tgt.PRODUCT_HEIGHT_CM = src.PRODUCT_HEIGHT_CM,
    tgt.PRODUCT_WIDTH_CM  = src.PRODUCT_WIDTH_CM,
    tgt.VOLUME_CM3        = src.VOLUME_CM3,
    tgt.UPDATED_AT        = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_WEIGHT_G, PRODUCT_LENGTH_CM,
     PRODUCT_HEIGHT_CM, PRODUCT_WIDTH_CM, VOLUME_CM3, LOADED_AT, UPDATED_AT)
VALUES
    (src.PRODUCT_ID, src.PRODUCT_CATEGORY, src.PRODUCT_WEIGHT_G, src.PRODUCT_LENGTH_CM,
     src.PRODUCT_HEIGHT_CM, src.PRODUCT_WIDTH_CM, src.VOLUME_CM3,
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.SILVER_LAYER.TASK_WATCHER_GEOLOCATION
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 */4 * * * America/New_York'
    WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.BRONZE_LAYER.GEOLOCATION_RAW_STREAM')
AS
MERGE INTO ECOMMERCE_DB.SILVER_LAYER.GEOLOCATION tgt
USING (
    SELECT
        GEOLOCATION_ZIP_CODE_PREFIX,
        AVG(GEOLOCATION_LAT)            AS GEOLOCATION_LAT,
        AVG(GEOLOCATION_LNG)            AS GEOLOCATION_LNG,
        INITCAP(TRIM(GEOLOCATION_CITY)) AS CITY,
        UPPER(TRIM(GEOLOCATION_STATE))  AS STATE
    FROM ECOMMERCE_DB.BRONZE_LAYER.GEOLOCATION_RAW_STREAM
    GROUP BY GEOLOCATION_ZIP_CODE_PREFIX, INITCAP(TRIM(GEOLOCATION_CITY)), UPPER(TRIM(GEOLOCATION_STATE))
) src
ON tgt.GEOLOCATION_ZIP_CODE_PREFIX = src.GEOLOCATION_ZIP_CODE_PREFIX
WHEN MATCHED THEN UPDATE SET
    tgt.GEOLOCATION_LAT = src.GEOLOCATION_LAT,
    tgt.GEOLOCATION_LNG = src.GEOLOCATION_LNG,
    tgt.CITY            = src.CITY,
    tgt.STATE           = src.STATE,
    tgt.UPDATED_AT      = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (GEOLOCATION_ZIP_CODE_PREFIX, GEOLOCATION_LAT, GEOLOCATION_LNG, CITY, STATE, LOADED_AT, UPDATED_AT)
VALUES
    (src.GEOLOCATION_ZIP_CODE_PREFIX, src.GEOLOCATION_LAT, src.GEOLOCATION_LNG,
     src.CITY, src.STATE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Resume all tasks
ALTER TASK ECOMMERCE_DB.SILVER_LAYER.TASK_MERGE_CUSTOMERS     RESUME;
ALTER TASK ECOMMERCE_DB.SILVER_LAYER.TASK_MERGE_SELLERS       RESUME;
ALTER TASK ECOMMERCE_DB.SILVER_LAYER.TASK_MERGE_PRODUCTS      RESUME;
ALTER TASK ECOMMERCE_DB.SILVER_LAYER.TASK_MERGE_GEOLOCATION   RESUME;
ALTER TASK ECOMMERCE_DB.SILVER_LAYER.TASK_WATCHER_CUSTOMERS   RESUME;
ALTER TASK ECOMMERCE_DB.SILVER_LAYER.TASK_WATCHER_SELLERS     RESUME;
ALTER TASK ECOMMERCE_DB.SILVER_LAYER.TASK_WATCHER_PRODUCTS    RESUME;
ALTER TASK ECOMMERCE_DB.SILVER_LAYER.TASK_WATCHER_GEOLOCATION RESUME;
