USE DATABASE ECOMMERCE_DB;

-- Create Schemas (Medallion Architecture)
CREATE SCHEMA IF NOT EXISTS BRONZE_LAYER;
CREATE SCHEMA IF NOT EXISTS SILVER_LAYER;
CREATE SCHEMA IF NOT EXISTS GOLD_LAYER;

-- File Formats for Bronze Layer Ingestion
CREATE OR REPLACE FILE FORMAT BRONZE_LAYER.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    COMPRESSION = 'AUTO';

CREATE OR REPLACE FILE FORMAT BRONZE_LAYER.JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE
    COMPRESSION = 'AUTO';

CREATE OR REPLACE FILE FORMAT BRONZE_LAYER.PARQUET_FORMAT
    TYPE = 'PARQUET'
    COMPRESSION = 'AUTO';