-- =========================================================
-- V1.1.6 - Silver layer dynamic tables (exact production SQL)
-- =========================================================

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.SILVER_LAYER.ORDERS (
	ORDER_ID,
	CUSTOMER_ID,
	ORDER_STATUS,
	ORDER_PURCHASE_TIMESTAMP,
	ORDER_APPROVED_AT,
	ORDER_DELIVERED_CARRIER_DATE,
	ORDER_DELIVERED_CUSTOMER_DATE,
	ORDER_ESTIMATED_DELIVERY_DATE,
	DELIVERY_DAYS,
	ESTIMATED_DELIVERY_DAYS,
	DELIVERY_PERFORMANCE
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    UPPER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CARRIER_DATE,
    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE,
    DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)  AS DELIVERY_DAYS,
    DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_ESTIMATED_DELIVERY_DATE) AS ESTIMATED_DELIVERY_DAYS,
    CASE
      WHEN ORDER_DELIVERED_CUSTOMER_DATE <= ORDER_ESTIMATED_DELIVERY_DATE THEN 'ON_TIME'
      WHEN ORDER_DELIVERED_CUSTOMER_DATE >  ORDER_ESTIMATED_DELIVERY_DATE THEN 'LATE'
      ELSE 'PENDING'
    END AS DELIVERY_PERFORMANCE
FROM ECOMMERCE_DB.BRONZE_LAYER.ORDERS_RAW
WHERE ORDER_ID IS NOT NULL;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.SILVER_LAYER.ORDER_ITEMS (
	ORDER_ID,
	ORDER_ITEM_ID,
	PRODUCT_ID,
	SELLER_ID,
	SHIPPING_LIMIT_DATE,
	PRICE,
	FREIGHT_VALUE,
	TOTAL_ITEM_VALUE
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE,
    ROUND(PRICE, 2)                    AS PRICE,
    ROUND(FREIGHT_VALUE, 2)            AS FREIGHT_VALUE,
    ROUND(PRICE + FREIGHT_VALUE, 2)    AS TOTAL_ITEM_VALUE
FROM ECOMMERCE_DB.BRONZE_LAYER.ORDER_ITEMS_RAW;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.SILVER_LAYER.ORDER_PAYMENTS (
	ORDER_ID,
	PAYMENT_SEQUENTIAL,
	PAYMENT_TYPE,
	PAYMENT_INSTALLMENTS,
	PAYMENT_VALUE
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    ORDER_ID,
    PAYMENT_SEQUENTIAL,
    UPPER(TRIM(PAYMENT_TYPE)) AS PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    ROUND(PAYMENT_VALUE, 2)   AS PAYMENT_VALUE
FROM ECOMMERCE_DB.BRONZE_LAYER.ORDER_PAYMENTS_RAW;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.SILVER_LAYER.ORDER_REVIEWS (
	REVIEW_ID,
	ORDER_ID,
	REVIEW_SCORE,
	REVIEW_COMMENT_TITLE,
	REVIEW_COMMENT_MESSAGE,
	REVIEW_CREATION_DATE,
	REVIEW_ANSWER_TIMESTAMP
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    TRIM(REVIEW_COMMENT_TITLE)   AS REVIEW_COMMENT_TITLE,
    TRIM(REVIEW_COMMENT_MESSAGE) AS REVIEW_COMMENT_MESSAGE,
    REVIEW_CREATION_DATE,
    REVIEW_ANSWER_TIMESTAMP
FROM ECOMMERCE_DB.BRONZE_LAYER.ORDER_REVIEWS_RAW
QUALIFY ROW_NUMBER() OVER (PARTITION BY REVIEW_ID ORDER BY REVIEW_CREATION_DATE DESC) = 1;
