-- =========================================================
-- V1.1.4 - Staging schema objects (exact production DDL + corrected FQNs)
-- =========================================================

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.STAGING_SCHEMA.STG_ORDERS (
	ORDER_ID VARCHAR(16777216) NOT NULL,
	CUSTOMER_ID VARCHAR(16777216),
	ORDER_STATUS VARCHAR(16777216),
	ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ(9),
	ORDER_APPROVED_AT TIMESTAMP_NTZ(9),
	ORDER_DELIVERED_CARRIER_DATE TIMESTAMP_NTZ(9),
	ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ(9),
	ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ(9),
	_RAW_INGESTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	_STG_LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	_STREAM_ACTION VARCHAR(16777216),
	CONSTRAINT PK_STG_ORDERS PRIMARY KEY (ORDER_ID)
);

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.STAGING_SCHEMA.TASK_PROCESS_ORDERS
	WAREHOUSE = SNOWFLAKE_LEARNING_WH
	SCHEDULE  = '15 MINUTE'
	WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.BRONZE_LAYER.STREAM_ORDERS')
AS
MERGE INTO ECOMMERCE_DB.STAGING_SCHEMA.STG_ORDERS AS tgt
USING (
    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        ORDER_STATUS,
        ORDER_PURCHASE_TIMESTAMP,
        ORDER_APPROVED_AT,
        ORDER_DELIVERED_CARRIER_DATE,
        ORDER_DELIVERED_CUSTOMER_DATE,
        ORDER_ESTIMATED_DELIVERY_DATE,
        CURRENT_TIMESTAMP() AS _INGESTED_AT,
        METADATA$ACTION AS STREAM_ACTION
    FROM ECOMMERCE_DB.BRONZE_LAYER.STREAM_ORDERS
    WHERE METADATA$ACTION = 'INSERT'
) AS src
ON tgt.ORDER_ID = src.ORDER_ID
WHEN MATCHED THEN UPDATE SET
    tgt.ORDER_STATUS                   = src.ORDER_STATUS,
    tgt.ORDER_DELIVERED_CARRIER_DATE   = src.ORDER_DELIVERED_CARRIER_DATE,
    tgt.ORDER_DELIVERED_CUSTOMER_DATE  = src.ORDER_DELIVERED_CUSTOMER_DATE,
    tgt._STG_LOADED_AT                 = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    ORDER_ID, CUSTOMER_ID, ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP, ORDER_APPROVED_AT,
    ORDER_DELIVERED_CARRIER_DATE, ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE, _RAW_INGESTED_AT, _STG_LOADED_AT, _STREAM_ACTION
) VALUES (
    src.ORDER_ID, src.CUSTOMER_ID, src.ORDER_STATUS,
    src.ORDER_PURCHASE_TIMESTAMP, src.ORDER_APPROVED_AT,
    src.ORDER_DELIVERED_CARRIER_DATE, src.ORDER_DELIVERED_CUSTOMER_DATE,
    src.ORDER_ESTIMATED_DELIVERY_DATE, src._INGESTED_AT, CURRENT_TIMESTAMP(), src.STREAM_ACTION
);

ALTER TASK ECOMMERCE_DB.STAGING_SCHEMA.TASK_PROCESS_ORDERS RESUME;
