-- =========================================================
-- V1.1.8 - Gold layer dynamic tables (exact production SQL)
-- Prereq: ECOMMERCE_DB.PUBLIC.PRIVACY_LEVEL tag created in V1.1.1
-- =========================================================

-- ---------- DIMENSIONS ----------

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.DIM_CUSTOMERS (
	CUSTOMER_ID        WITH TAG (ECOMMERCE_DB.PUBLIC.PRIVACY_LEVEL = 'HIGH'),
	CUSTOMER_UNIQUE_ID WITH TAG (ECOMMERCE_DB.PUBLIC.PRIVACY_LEVEL = 'HIGH'),
	ZIP_CODE           WITH TAG (ECOMMERCE_DB.PUBLIC.PRIVACY_LEVEL = 'MEDIUM'),
	CITY               WITH TAG (ECOMMERCE_DB.PUBLIC.PRIVACY_LEVEL = 'MEDIUM'),
	STATE              WITH TAG (ECOMMERCE_DB.PUBLIC.PRIVACY_LEVEL = 'LOW'),
	LOADED_AT,
	UPDATED_AT
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    CUSTOMER_ID,
    TRIM(REPLACE(CUSTOMER_UNIQUE_ID, '"', '')) AS CUSTOMER_UNIQUE_ID,
    ZIP_CODE,
    CITY,
    STATE,
    LOADED_AT,
    UPDATED_AT
FROM ECOMMERCE_DB.SILVER_LAYER.CUSTOMERS;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.DIM_SELLERS (
	SELLER_ID,
	ZIP_CODE WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'POSTAL_CODE'),
	CITY,
	STATE,
	LOADED_AT,
	UPDATED_AT
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM ECOMMERCE_DB.SILVER_LAYER.SELLERS;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.DIM_PRODUCTS (
	PRODUCT_ID,
	PRODUCT_CATEGORY,
	PRODUCT_WEIGHT_G,
	PRODUCT_LENGTH_CM,
	PRODUCT_HEIGHT_CM,
	PRODUCT_WIDTH_CM,
	VOLUME_CM3,
	LOADED_AT,
	UPDATED_AT
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM ECOMMERCE_DB.SILVER_LAYER.PRODUCTS;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.DIM_GEOLOCATION (
	GEOLOCATION_ZIP_CODE_PREFIX WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'POSTAL_CODE'),
	GEOLOCATION_LAT             WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'LATITUDE'),
	GEOLOCATION_LNG,
	CITY,
	STATE,
	LOADED_AT,
	UPDATED_AT
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM ECOMMERCE_DB.SILVER_LAYER.GEOLOCATION;

-- ---------- FACTS ----------

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.FACT_ORDERS (
	ORDER_ID,
	CUSTOMER_ID,
	ORDER_STATUS,
	ORDER_PURCHASE_TIMESTAMP,
	ORDER_APPROVED_AT,
	ORDER_DELIVERED_CARRIER_DATE,
	ORDER_DELIVERED_CUSTOMER_DATE,
	ORDER_ESTIMATED_DELIVERY_DATE,
	DELIVERY_DAYS,
	ESTIMATED_DELIVERY_DAYS,
	DELIVERY_PERFORMANCE
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM ECOMMERCE_DB.SILVER_LAYER.ORDERS;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.FACT_ORDER_ITEMS (
	ORDER_ID,
	ORDER_ITEM_ID,
	PRODUCT_ID,
	SELLER_ID,
	SHIPPING_LIMIT_DATE,
	PRICE,
	FREIGHT_VALUE,
	TOTAL_ITEM_VALUE
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM ECOMMERCE_DB.SILVER_LAYER.ORDER_ITEMS;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.FACT_ORDER_PAYMENTS (
	ORDER_ID,
	PAYMENT_SEQUENTIAL,
	PAYMENT_TYPE,
	PAYMENT_INSTALLMENTS,
	PAYMENT_VALUE
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM ECOMMERCE_DB.SILVER_LAYER.ORDER_PAYMENTS;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.FACT_ORDER_REVIEWS (
	REVIEW_ID,
	ORDER_ID,
	REVIEW_SCORE,
	REVIEW_COMMENT_TITLE,
	REVIEW_COMMENT_MESSAGE,
	REVIEW_COMMENT_MESSAGE_EN,
	REVIEW_CREATION_DATE,
	REVIEW_ANSWER_TIMESTAMP
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE,
    CASE
        WHEN REVIEW_COMMENT_MESSAGE IS NOT NULL
        THEN SNOWFLAKE.CORTEX.TRANSLATE(REVIEW_COMMENT_MESSAGE, 'pt', 'en')
        ELSE NULL
    END AS REVIEW_COMMENT_MESSAGE_EN,
    REVIEW_CREATION_DATE,
    REVIEW_ANSWER_TIMESTAMP
FROM ECOMMERCE_DB.SILVER_LAYER.ORDER_REVIEWS;

-- ---------- AGGREGATES ----------

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.CUSTOMER_360 (
	CUSTOMER_ID,
	CUSTOMER_UNIQUE_ID,
	CITY,
	STATE,
	TOTAL_ORDERS,
	FIRST_ORDER_DATE,
	LAST_ORDER_DATE,
	LIFETIME_VALUE,
	AVG_ORDER_VALUE,
	AVG_REVIEW_SCORE,
	CUSTOMER_SEGMENT
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_UNIQUE_ID,
    c.CITY,
    c.STATE,
    COUNT(DISTINCT o.ORDER_ID)         AS TOTAL_ORDERS,
    MIN(o.ORDER_PURCHASE_TIMESTAMP)    AS FIRST_ORDER_DATE,
    MAX(o.ORDER_PURCHASE_TIMESTAMP)    AS LAST_ORDER_DATE,
    ROUND(SUM(p.PAYMENT_VALUE), 2)     AS LIFETIME_VALUE,
    ROUND(AVG(p.PAYMENT_VALUE), 2)     AS AVG_ORDER_VALUE,
    ROUND(AVG(r.REVIEW_SCORE), 2)      AS AVG_REVIEW_SCORE,
    CASE
        WHEN COUNT(DISTINCT o.ORDER_ID) >= 5 THEN 'CHAMPION'
        WHEN COUNT(DISTINCT o.ORDER_ID) >= 3 THEN 'LOYAL'
        WHEN COUNT(DISTINCT o.ORDER_ID) >= 2 THEN 'REPEAT'
        ELSE 'NEW'
    END AS CUSTOMER_SEGMENT
FROM ECOMMERCE_DB.SILVER_LAYER.CUSTOMERS c
LEFT JOIN ECOMMERCE_DB.SILVER_LAYER.ORDERS         o ON c.CUSTOMER_ID = o.CUSTOMER_ID
LEFT JOIN ECOMMERCE_DB.SILVER_LAYER.ORDER_PAYMENTS p ON o.ORDER_ID    = p.ORDER_ID
LEFT JOIN ECOMMERCE_DB.SILVER_LAYER.ORDER_REVIEWS  r ON o.ORDER_ID    = r.ORDER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_UNIQUE_ID, c.CITY, c.STATE;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.DAILY_SALES_SUMMARY (
	ORDER_DATE,
	TOTAL_ORDERS,
	UNIQUE_CUSTOMERS,
	GROSS_REVENUE,
	TOTAL_FREIGHT,
	NET_PRODUCT_REVENUE,
	AVG_ITEM_VALUE
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    DATE_TRUNC('day', o.ORDER_PURCHASE_TIMESTAMP)::DATE AS ORDER_DATE,
    COUNT(DISTINCT o.ORDER_ID)                          AS TOTAL_ORDERS,
    COUNT(DISTINCT o.CUSTOMER_ID)                       AS UNIQUE_CUSTOMERS,
    SUM(oi.TOTAL_ITEM_VALUE)                            AS GROSS_REVENUE,
    SUM(oi.FREIGHT_VALUE)                               AS TOTAL_FREIGHT,
    SUM(oi.PRICE)                                       AS NET_PRODUCT_REVENUE,
    AVG(oi.TOTAL_ITEM_VALUE)                            AS AVG_ITEM_VALUE
FROM ECOMMERCE_DB.SILVER_LAYER.ORDERS o
JOIN ECOMMERCE_DB.SILVER_LAYER.ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
GROUP BY 1;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.PRODUCT_ANALYTICS (
	PRODUCT_ID,
	PRODUCT_CATEGORY,
	TIMES_ORDERED,
	TOTAL_REVENUE,
	AVG_SELLING_PRICE,
	AVG_REVIEW_SCORE,
	PRODUCT_WEIGHT_G,
	VOLUME_CM3
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_CATEGORY,
    COUNT(DISTINCT oi.ORDER_ID)        AS TIMES_ORDERED,
    ROUND(SUM(oi.PRICE), 2)            AS TOTAL_REVENUE,
    ROUND(AVG(oi.PRICE), 2)            AS AVG_SELLING_PRICE,
    ROUND(AVG(r.REVIEW_SCORE), 2)      AS AVG_REVIEW_SCORE,
    p.PRODUCT_WEIGHT_G,
    p.VOLUME_CM3
FROM ECOMMERCE_DB.SILVER_LAYER.PRODUCTS p
LEFT JOIN ECOMMERCE_DB.SILVER_LAYER.ORDER_ITEMS   oi ON p.PRODUCT_ID = oi.PRODUCT_ID
LEFT JOIN ECOMMERCE_DB.SILVER_LAYER.ORDERS         o ON oi.ORDER_ID  = o.ORDER_ID
LEFT JOIN ECOMMERCE_DB.SILVER_LAYER.ORDER_REVIEWS  r ON o.ORDER_ID   = r.ORDER_ID
GROUP BY 1, 2, 7, 8;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.SELLER_PERFORMANCE (
	SELLER_ID,
	SELLER_CITY,
	SELLER_STATE,
	TOTAL_ORDERS,
	TOTAL_ITEMS_SOLD,
	TOTAL_REVENUE,
	AVG_ITEM_PRICE,
	AVG_REVIEW_SCORE,
	LATE_DELIVERIES,
	LATE_DELIVERY_PCT
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    s.SELLER_ID,
    s.CITY                                                               AS SELLER_CITY,
    s.STATE                                                              AS SELLER_STATE,
    COUNT(DISTINCT oi.ORDER_ID)                                          AS TOTAL_ORDERS,
    COUNT(oi.ORDER_ITEM_ID)                                              AS TOTAL_ITEMS_SOLD,
    ROUND(SUM(oi.PRICE), 2)                                              AS TOTAL_REVENUE,
    ROUND(AVG(oi.PRICE), 2)                                              AS AVG_ITEM_PRICE,
    ROUND(AVG(r.REVIEW_SCORE), 2)                                        AS AVG_REVIEW_SCORE,
    SUM(CASE WHEN o.DELIVERY_PERFORMANCE = 'LATE' THEN 1 ELSE 0 END)    AS LATE_DELIVERIES,
    ROUND(
        SUM(CASE WHEN o.DELIVERY_PERFORMANCE = 'LATE' THEN 1 ELSE 0 END)
        / NULLIF(COUNT(DISTINCT oi.ORDER_ID), 0) * 100, 2
    )                                                                    AS LATE_DELIVERY_PCT
FROM ECOMMERCE_DB.SILVER_LAYER.SELLERS s
JOIN ECOMMERCE_DB.SILVER_LAYER.ORDER_ITEMS    oi ON s.SELLER_ID  = oi.SELLER_ID
JOIN ECOMMERCE_DB.SILVER_LAYER.ORDERS          o ON oi.ORDER_ID  = o.ORDER_ID
LEFT JOIN ECOMMERCE_DB.SILVER_LAYER.ORDER_REVIEWS r ON o.ORDER_ID = r.ORDER_ID
GROUP BY s.SELLER_ID, s.CITY, s.STATE;

CREATE OR ALTER DYNAMIC TABLE ECOMMERCE_DB.GOLD_LAYER.PAYMENT_ANALYSIS (
	ORDER_MONTH,
	PAYMENT_TYPE,
	ORDER_COUNT,
	TOTAL_VALUE,
	AVG_VALUE,
	AVG_INSTALLMENTS
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = COMPUTE_WH
AS
SELECT
    DATE_TRUNC('month', o.ORDER_PURCHASE_TIMESTAMP)::DATE AS ORDER_MONTH,
    p.PAYMENT_TYPE,
    COUNT(DISTINCT p.ORDER_ID)                            AS ORDER_COUNT,
    ROUND(SUM(p.PAYMENT_VALUE), 2)                        AS TOTAL_VALUE,
    ROUND(AVG(p.PAYMENT_VALUE), 2)                        AS AVG_VALUE,
    ROUND(AVG(p.PAYMENT_INSTALLMENTS), 2)                 AS AVG_INSTALLMENTS
FROM ECOMMERCE_DB.SILVER_LAYER.ORDER_PAYMENTS p
JOIN ECOMMERCE_DB.SILVER_LAYER.ORDERS o ON p.ORDER_ID = o.ORDER_ID
GROUP BY 1, 2;
