-- =========================================================
-- V1.1.3 - Streams on bronze tables (CDC for silver merges)
-- =========================================================

CREATE OR REPLACE STREAM ECOMMERCE_DB.BRONZE_LAYER.CUSTOMER_RAW_STREAM
    ON TABLE ECOMMERCE_DB.BRONZE_LAYER.CUSTOMER_RAW;

CREATE OR REPLACE STREAM ECOMMERCE_DB.BRONZE_LAYER.GEOLOCATION_RAW_STREAM
    ON TABLE ECOMMERCE_DB.BRONZE_LAYER.GEOLOCATION_RAW;

CREATE OR REPLACE STREAM ECOMMERCE_DB.BRONZE_LAYER.SELLERS_RAW_STREAM
    ON TABLE ECOMMERCE_DB.BRONZE_LAYER.SELLERS_RAW;

CREATE OR REPLACE STREAM ECOMMERCE_DB.BRONZE_LAYER.PRODUCTS_RAW_STREAM
    ON TABLE ECOMMERCE_DB.BRONZE_LAYER.PRODUCTS_RAW;

CREATE OR REPLACE STREAM ECOMMERCE_DB.BRONZE_LAYER.PRODUCT_CATEGORY_TRANSLATION_RAW_STREAM
    ON TABLE ECOMMERCE_DB.BRONZE_LAYER.PRODUCT_CATEGORY_TRANSLATION_RAW;

CREATE OR REPLACE STREAM ECOMMERCE_DB.BRONZE_LAYER.STREAM_ORDERS
    ON TABLE ECOMMERCE_DB.BRONZE_LAYER.ORDERS_RAW
    APPEND_ONLY = TRUE;