-- Migration: Create Bronze Layer Tables (Raw Data)
-- Database: ECOMMERCE_DB

-- USE DATABASE ECOMMERCE_DB;
-- USE SCHEMA BRONZE_LAYER;

-- =========================================================
-- V1.1.2 - Bronze layer raw tables (landing zone)
-- =========================================================

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.CUSTOMER_RAW (
	CUSTOMER_ID VARCHAR(16777216),
	CUSTOMER_UNIQUE_ID VARCHAR(16777216),
	CUSTOMER_ZIP_CODE_PREFIX VARCHAR(16777216),
	CUSTOMER_CITY VARCHAR(16777216),
	CUSTOMER_STATE VARCHAR(16777216)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.GEOLOCATION_RAW (
	GEOLOCATION_ZIP_CODE_PREFIX VARCHAR(16777216) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='POSTAL_CODE'),
	GEOLOCATION_LAT FLOAT WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='LATITUDE'),
	GEOLOCATION_LNG FLOAT,
	GEOLOCATION_CITY VARCHAR(16777216),
	GEOLOCATION_STATE VARCHAR(16777216)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.SELLERS_RAW (
	SELLER_ID VARCHAR(16777216),
	SELLER_ZIP_CODE_PREFIX VARCHAR(16777216) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='POSTAL_CODE'),
	SELLER_CITY VARCHAR(16777216),
	SELLER_STATE VARCHAR(16777216)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.ORDERS_RAW (
	ORDER_ID VARCHAR(16777216),
	CUSTOMER_ID VARCHAR(16777216),
	ORDER_STATUS VARCHAR(16777216),
	ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ(9),
	ORDER_APPROVED_AT TIMESTAMP_NTZ(9),
	ORDER_DELIVERED_CARRIER_DATE TIMESTAMP_NTZ(9),
	ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ(9),
	ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ(9)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.ORDER_ITEMS_RAW (
	ORDER_ID VARCHAR(16777216),
	ORDER_ITEM_ID NUMBER(38,0),
	PRODUCT_ID VARCHAR(16777216),
	SELLER_ID VARCHAR(16777216),
	SHIPPING_LIMIT_DATE TIMESTAMP_NTZ(9),
	PRICE FLOAT,
	FREIGHT_VALUE FLOAT
);

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.ORDER_PAYMENTS_RAW (
	ORDER_ID VARCHAR(16777216),
	PAYMENT_SEQUENTIAL NUMBER(38,0),
	PAYMENT_TYPE VARCHAR(16777216),
	PAYMENT_INSTALLMENTS NUMBER(38,0),
	PAYMENT_VALUE FLOAT
);

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.ORDER_REVIEWS_RAW (
	REVIEW_ID VARCHAR(16777216),
	ORDER_ID VARCHAR(16777216),
	REVIEW_SCORE NUMBER(38,0),
	REVIEW_COMMENT_TITLE VARCHAR(16777216),
	REVIEW_COMMENT_MESSAGE VARCHAR(16777216),
	REVIEW_CREATION_DATE TIMESTAMP_NTZ(9),
	REVIEW_ANSWER_TIMESTAMP TIMESTAMP_NTZ(9)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.PRODUCTS_RAW (
	PRODUCT_ID VARCHAR(16777216),
	PRODUCT_CATEGORY_NAME VARCHAR(16777216),
	PRODUCT_NAME_LENGHT NUMBER(38,0),
	PRODUCT_DESCRIPTION_LENGHT NUMBER(38,0),
	PRODUCT_PHOTOS_QTY NUMBER(38,0),
	PRODUCT_WEIGHT_G FLOAT,
	PRODUCT_LENGTH_CM FLOAT,
	PRODUCT_HEIGHT_CM FLOAT,
	PRODUCT_WIDTH_CM FLOAT
);

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.PRODUCT_CATEGORY_TRANSLATION_RAW (
	PRODUCT_CATEGORY_NAME VARCHAR(16777216),
	PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(16777216)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.PRODUCT_CATEGORY_TRANSLATION_ING (
	PRODUCT_CATEGORY VARCHAR(16777216),
	PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(16777216)
);


-- -- External Stage for S3
-- CREATE OR REPLACE STAGE BRONZE_LAYER.S3_ECOMMERCE_STAGE
--     URL = 's3://your-bucket-name/ecommerce/'
--     FILE_FORMAT = BRONZE_LAYER.CSV_FORMAT;

-- -- Snowpipe for Real-Time Ingestion (Orders)
-- CREATE OR REPLACE PIPE BRONZE_LAYER.ORDERS_PIPE
--     AUTO_INGEST = TRUE
--     AS
--     COPY INTO BRONZE_LAYER.RAW_ORDERS
--     FROM @BRONZE_LAYER.S3_ECOMMERCE_STAGE/orders/
--     FILE_FORMAT = BRONZE_LAYER.CSV_FORMAT
--     MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- -- Snowpipe for Real-Time Ingestion (Payments)
-- CREATE OR REPLACE PIPE BRONZE_LAYER.PAYMENTS_PIPE
--     AUTO_INGEST = TRUE
--     AS
--     COPY INTO BRONZE_LAYER.RAW_PAYMENTS
--     FROM @BRONZE_LAYER.S3_ECOMMERCE_STAGE/payments/
--     FILE_FORMAT = BRONZE_LAYER.CSV_FORMAT
--     MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
