-- =========================================================
-- V1.1.5 - Silver layer standard tables (exact production DDL)
-- =========================================================

CREATE OR REPLACE TABLE ECOMMERCE_DB.SILVER_LAYER.CUSTOMERS (
	CUSTOMER_ID VARCHAR(16777216) NOT NULL,
	CUSTOMER_UNIQUE_ID VARCHAR(16777216),
	ZIP_CODE VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

CREATE OR REPLACE TABLE ECOMMERCE_DB.SILVER_LAYER.GEOLOCATION (
	GEOLOCATION_ZIP_CODE_PREFIX VARCHAR(16777216) NOT NULL WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='POSTAL_CODE'),
	GEOLOCATION_LAT FLOAT WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='LATITUDE'),
	GEOLOCATION_LNG FLOAT,
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ECOMMERCE_DB.SILVER_LAYER.SELLERS (
	SELLER_ID VARCHAR(16777216) NOT NULL,
	ZIP_CODE VARCHAR(16777216) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='QUASI_IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='POSTAL_CODE'),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_SELLERS PRIMARY KEY (SELLER_ID)
);

CREATE OR REPLACE TABLE ECOMMERCE_DB.SILVER_LAYER.PRODUCTS (
	PRODUCT_ID VARCHAR(16777216) NOT NULL,
	PRODUCT_CATEGORY VARCHAR(16777216),
	PRODUCT_WEIGHT_G FLOAT,
	PRODUCT_LENGTH_CM FLOAT,
	PRODUCT_HEIGHT_CM FLOAT,
	PRODUCT_WIDTH_CM FLOAT,
	VOLUME_CM3 FLOAT,
	LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID)
);
