CREATE OR ALTER DYNAMIC TABLE SILVER_LAYER.ORDERS (
	ORDER_ID,
	CUSTOMER_ID,
	ORDER_STATUS,
	ORDER_PURCHASE_TIMESTAMP,
	ORDER_APPROVED_AT,
	ORDER_DELIVERED_CARRIER_DATE,
	ORDER_DELIVERED_CUSTOMER_DATE,
	ORDER_ESTIMATED_DELIVERY_DATE,
	DELIVERY_DAYS,
	ESTIMATED_DELIVERY_DAYS,
	DELIVERY_PERFORMANCE
)
	TARGET_LAG = '1 hour' REFRESH_MODE = AUTO INITIALIZE = ON_CREATE WAREHOUSE = SNOWFLAKE_LEARNING_WH
AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    UPPER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CARRIER_DATE,
    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE,
    DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)  AS DELIVERY_DAYS,
    DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_ESTIMATED_DELIVERY_DATE) AS ESTIMATED_DELIVERY_DAYS,
    CASE
      WHEN ORDER_DELIVERED_CUSTOMER_DATE <= ORDER_ESTIMATED_DELIVERY_DATE THEN 'ON_TIME'
      WHEN ORDER_DELIVERED_CUSTOMER_DATE >  ORDER_ESTIMATED_DELIVERY_DATE THEN 'LATE'
      ELSE 'PENDING'
    END AS DELIVERY_PERFORMANCE
FROM BRONZE_LAYER.ORDERS_RAW
WHERE ORDER_ID IS NOT NULL;

